---
kind: pipeline
type: kubernetes
name: run-tests

clone:
  disable: true
  
workspace:
  path: /go/src/github.com/gravitational/teleport-plugins
  
trigger:
  event:
    - pull_request  

steps: 
- name: Run tests
  image: golang:1.13.2
  commands:
    - git clone https://github.com/gravitational/teleport-plugins.git .
    - git checkout $DRONE_COMMIT
    - go get -v -t -d ./...
    - cd access && go test ./...

---
kind: pipeline
type: kubernetes
name: build-artifacts

depends_on:
  - run-tests
    
workspace:
  path: /go/src/github.com/gravitational/teleport-plugins
  
trigger:
  event:
    - pull_request

steps:
  - name: Build artifacts
    image: golang:1.13.2
    commands:
      - git clone https://github.com/gravitational/teleport-plugins.git .
      - git checkout $DRONE_COMMIT
      - go get -v -t -d ./...
      - mkdir -p build/
      - make release-all
      - find . -iname "*.tar.gz" -exec cp {} build/ \;

  - name: Upload to S3
    image: plugins/s3
    settings:
      bucket:
        from_secret: AWS_S3_BUCKET
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: us-west-2
      source: /go/src/github.com/gravitational/teleport-plugins/build/*.tar.gz
      target: /plugins/drone/pr/${DRONE_PULL_REQUEST}
    strip_prefix: /go/src/github.com/gravitational/teleport-plugins/build
