---
kind: pipeline
type: kubernetes
name: test-linux

trigger:
  branch:
    - master
    - branch/*
  event:
    include:
      - push
      - pull_request
  repo:
    include:
      - gravitational/*

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

steps:
  - name: Run linter
    image: golangci/golangci-lint:v1.27.0
    commands:
      - make lint

  - name: Run tests
    image: golang:1.14.4
    commands:
      - make test

---
kind: pipeline
type: exec
name: test-darwin

concurrency:
  limit: 1

platform:
  os: darwin
  arch: amd64

trigger:
  branch:
    - master
    - branch/*
  event:
    include:
      - push
      - pull_request
  repo:
    include:
      - gravitational/*

workspace:
  path: /tmp/teleport-plugins

steps:
  - name: Clean up exec runner storage (pre)
    commands:
      - rm -rf test-darwin
      - mkdir -p test-darwin/go/cache
      - chmod -R u+rw test-darwin

  - name: Run tests
    environment:
      GOPATH: /tmp/teleport-plugins/test-darwin/go
      GOCACHE: /tmp/teleport-plugins/test-darwin/go/cache
    commands:
      - make test

  - name: Clean up exec runner storage (post)
    commands:
      - rm -rf test-darwin

---
kind: pipeline
type: kubernetes
name: build-linux

trigger:
  event:
    - tag
  ref:
    include:
      - refs/tags/teleport-*-v*

depends_on:
  - test-linux

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

steps:
  - name: Build artifacts
    image: golang:1.14.4
    commands:
      - mkdir -p build/
      - export PLUGIN_TYPE=$(echo ${DRONE_TAG} | cut -d- -f2)
      - make release/access-$PLUGIN_TYPE
      - find access/ -iname "*.tar.gz" -print -exec cp {} build/ \;
      - cd build
      - for FILE in *.tar.gz; do sha256sum $FILE > $FILE.sha256; done
      - ls -l .

  - name: Upload to S3
    image: plugins/s3
    settings:
      bucket:
        from_secret: AWS_S3_BUCKET
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: us-west-2
      source: /go/src/github.com/gravitational/teleport-plugins/build/*
      target: teleport-plugins/tag/${DRONE_TAG}
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/build

---
kind: pipeline
type: kubernetes
name: promote-artifact

trigger:
  event:
    - promote
  target:
    - production

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
  - name: Download artifact from S3 artifact publishing bucket
    image: amazon/aws-cli
    environment:
      AWS_S3_BUCKET:
        from_secret: AWS_S3_BUCKET
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION: us-west-2
    commands:
      - aws s3 sync s3://$AWS_S3_BUCKET/teleport-plugins/tag/${DRONE_TAG}/ .

  - name: Upload artifact to production S3 bucket with public read access
    image: plugins/s3
    settings:
      bucket:
        from_secret: PRODUCTION_AWS_S3_BUCKET
      access_key:
        from_secret: PRODUCTION_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: PRODUCTION_AWS_SECRET_ACCESS_KEY
      region: us-east-1
      acl: public-read
      source: /go/src/github.com/gravitational/teleport-plugins/*
      target: teleport-plugins/${DRONE_TAG##*-v}/
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/

---
kind: signature
hmac: 7ba0986b68dfc1c5dc1d21a1540b451385c3cd7f6165aeab1a21b92726c3e3c0

...
