---
kind: pipeline
type: kubernetes
name: tag-build-terraform-linux

trigger:
  event:
    - tag
  ref:
    include:
      - refs/tags/terraform-provider-teleport-v*

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

steps:
  - name: Build artifacts
    image: golang:1.17.5
    commands:
      - mkdir -p build/
      - make release/terraform
      - find terraform/ -iname "*.tar.gz" -print -exec cp {} build/ \;
      - cd build
      - for FILE in *.tar.gz; do sha256sum $FILE > $FILE.sha256; done
      - ls -l .

  - name: Upload to S3
    image: plugins/s3
    settings:
      bucket:
        from_secret: AWS_S3_BUCKET
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: us-east-2
      source: /go/src/github.com/gravitational/teleport-plugins/build/*
      target: teleport-plugins/tag/${DRONE_TAG}
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/build

---
kind: pipeline
type: kubernetes
name: stage-terraform-provider-registry

trigger:
  event:
    - tag
  ref:
    include:
      - refs/tags/terraform-provider-teleport-v*

depends_on:
  - tag-build-terraform-linux
#  - tag-build-terraform-darwin

concurrency:
  limit: 1

steps:
  - name: Upload terraform provider to staging registry
    image: golang:1.17.5
    commands:
      - cd tooling
      - |
        go run ./cmd/promote-terraform   \
          --tag ${DRONE_TAG}             \
          -p 4.0 -p 5.1                  \
          --namespace gravitational      \
          --name teleport

    environment:
      STAGING_REGION: us-east-2
      STAGING_BUCKET:
        from_secret: AWS_S3_BUCKET
      STAGING_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      STAGING_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      
      PRODUCTION_REGION: us-east-2
      PROD_BUCKET:
        from_secret: STAGING_AWS_TERRAFORM_BUCKET
      PROD_ACCESS_KEY_ID:
        from_secret: STAGING_AWS_TERRAFORM_ACCESS_KEY_ID
      PROD_SECRET_ACCESS_KEY:
        from_secret: STAGING_AWS_TERRAFORM_SECRET_ACCESS_KEY
      
      SIGNING_KEY:
        from_secret: STAGING_TERRAFORM_REGISTRY_SIGNING_KEY
---
kind: pipeline
type: kubernetes
name: promote-terraform-provider

trigger:
  event:
  - promote
  target:
  - production

concurrency:
  limit: 1

steps:
  - name: Promote terraform provider to public registry
    image: golang:1.17.5
    commands:
      - cd tooling
      - |
        go run ./cmd/promote-terraform   \
          --tag ${DRONE_TAG}             \
          -p 4.0 -p 5.1                  \
          --namespace gravitational      \
          --name teleport

    environment:
      STAGING_REGION: us-east-2
      STAGING_BUCKET:
        from_secret: AWS_S3_BUCKET
      STAGING_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      STAGING_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      
      PRODUCTION_REGION: ap-southeast-2
      PROD_BUCKET:
        from_secret: PRODUCTION_AWS_TERRAFORM_BUCKET
      PROD_ACCESS_KEY_ID:
        from_secret: PRODUCTION_AWS_TERRAFORM_ACCESS_KEY_ID
      PROD_SECRET_ACCESS_KEY:
        from_secret: PRODUCTION_AWS_TERRAFORM_SECRET_ACCESS_KEY 

      SIGNING_KEY:
        from_secret: PRODUCTION_TERRAFORM_REGISTRY_SIGNING_KEY 

---
kind: signature
hmac: 0da8f5b80ad340c206367ddc7b64f44b4c22ee0b81e4fe4179491c04754bb82a

...
