---
kind: pipeline
type: kubernetes
name: lint

trigger:
  event:
    - pull_request
    - tag

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
- name: Run linter
  image: golangci/golangci-lint:v1.27.0
  commands:
    - git clone https://github.com/gravitational/teleport-plugins.git .
    - git checkout $DRONE_COMMIT
    - make lint

---
kind: pipeline
type: kubernetes
name: test

trigger:
  event:
    - pull_request
    - tag

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
- name: Restore cache
  image: meltwater/drone-cache
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  settings:
    restore: true
    bucket:
      from_secret: AWS_S3_BUCKET
    region: us-west-2
    mount:
      - '/root/.cache/go-build'

- name: Run tests
  image: golang:1.13.2
  commands:
    - git clone https://github.com/gravitational/teleport-plugins.git .
    - git checkout $DRONE_COMMIT
    - make test

- name: Save cache
  image: meltwater/drone-cache
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  settings:
    rebuild: true
    bucket:
      from_secret: AWS_S3_BUCKET
    region: us-west-2
    mount:
      - '/root/.cache/go-build'

---
kind: pipeline
type: kubernetes
name: build-jira

depends_on:
  - lint
  - test

trigger:
  event:
    - tag
  ref:
    include:
      - refs/tags/teleport-jira-*

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
  - name: Build artifacts
    image: golang:1.13.2
    commands:
      - git clone https://github.com/gravitational/teleport-plugins.git .
      - git fetch --all --tags
      - git checkout $DRONE_TAG
      - mkdir -p build/
      - make release/access-jira
      - find access/ -iname "*.tar.gz" -print -exec cp {} build/ \;
      - cd build
      - for FILE in *.tar.gz; do sha256sum $FILE > $FILE.sha256; done
      - ls -l .

  - name: Upload to S3
    image: plugins/s3
    settings:
      bucket:
        from_secret: AWS_S3_BUCKET
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: us-west-2
      source: /go/src/github.com/gravitational/teleport-plugins/build/*
      target: teleport-plugins/tag/${DRONE_TAG}
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/build

---
kind: pipeline
type: kubernetes
name: build-slack

depends_on:
  - lint
  - test

trigger:
  event:
    - tag
  ref:
    include:
      - refs/tags/teleport-slack-*

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
  - name: Build artifacts
    image: golang:1.13.2
    commands:
      - git clone https://github.com/gravitational/teleport-plugins.git .
      - git fetch --all --tags
      - git checkout $DRONE_TAG
      - mkdir -p build/
      - make release/access-slack
      - find access/ -iname "*.tar.gz" -print -exec cp {} build/ \;
      - cd build
      - for FILE in *.tar.gz; do sha256sum $FILE > $FILE.sha256; done
      - ls -l .

  - name: Upload to S3
    image: plugins/s3
    settings:
      bucket:
        from_secret: AWS_S3_BUCKET
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: us-west-2
      source: /go/src/github.com/gravitational/teleport-plugins/build/*
      target: teleport-plugins/tag/${DRONE_TAG}
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/build

---
kind: pipeline
type: kubernetes
name: build-mattermost

depends_on:
  - lint
  - test

trigger:
  event:
    - tag
  ref:
    include:
      - refs/tags/teleport-mattermost-*

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
  - name: Build artifacts
    image: golang:1.13.2
    commands:
      - git clone https://github.com/gravitational/teleport-plugins.git .
      - git fetch --all --tags
      - git checkout $DRONE_TAG
      - mkdir -p build/
      - make release/access-mattermost
      - find access/ -iname "*.tar.gz" -print -exec cp {} build/ \;
      - cd build
      - for FILE in *.tar.gz; do sha256sum $FILE > $FILE.sha256; done
      - ls -l .

  - name: Upload to S3
    image: plugins/s3
    settings:
      bucket:
        from_secret: AWS_S3_BUCKET
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: us-west-2
      source: /go/src/github.com/gravitational/teleport-plugins/build/*
      target: teleport-plugins/tag/${DRONE_TAG}
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/build

---
kind: pipeline
type: kubernetes
name: build-pagerduty

depends_on:
  - lint
  - test

trigger:
  event:
    - tag
  ref:
    include:
      - refs/tags/teleport-pagerduty-*

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
  - name: Build artifacts
    image: golang:1.13.2
    commands:
      - git clone https://github.com/gravitational/teleport-plugins.git .
      - git fetch --all --tags
      - git checkout $DRONE_TAG
      - mkdir -p build/
      - make release/access-pagerduty
      - find access/ -iname "*.tar.gz" -print -exec cp {} build/ \;
      - cd build
      - for FILE in *.tar.gz; do sha256sum $FILE > $FILE.sha256; done
      - ls -l .

  - name: Upload to S3
    image: plugins/s3
    settings:
      bucket:
        from_secret: AWS_S3_BUCKET
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: us-west-2
      source: /go/src/github.com/gravitational/teleport-plugins/build/*
      target: teleport-plugins/tag/${DRONE_TAG}
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/build

---
kind: pipeline
type: kubernetes
name: build-gitlab

depends_on:
  - lint
  - test

trigger:
  event:
    - tag
  ref:
    include:
      - refs/tags/teleport-gitlab-*

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
  - name: Build artifacts
    image: golang:1.13.2
    commands:
      - git clone https://github.com/gravitational/teleport-plugins.git .
      - git fetch --all --tags
      - git checkout $DRONE_TAG
      - mkdir -p build/
      - make release/access-gitlab
      - find access/ -iname "*.tar.gz" -print -exec cp {} build/ \;
      - cd build
      - for FILE in *.tar.gz; do sha256sum $FILE > $FILE.sha256; done
      - ls -l .

  - name: Upload to S3
    image: plugins/s3
    settings:
      bucket:
        from_secret: AWS_S3_BUCKET
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: us-west-2
      source: /go/src/github.com/gravitational/teleport-plugins/build/*
      target: teleport-plugins/tag/${DRONE_TAG}
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/build

---
kind: pipeline
type: kubernetes
name: promote-artifact

trigger:
  event:
    - promote
  target:
    - production

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
  - name: Download artifact from S3 artifact publishing bucket
    image: amazon/aws-cli
    environment:
      AWS_S3_BUCKET:
        from_secret: AWS_S3_BUCKET
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION: us-west-2
    commands:
      - aws s3 sync s3://$AWS_S3_BUCKET/teleport-plugins/tag/$DRONE_TAG/ .

  - name: Upload artifact to production S3 bucket with public read access
    image: plugins/s3
    settings:
      bucket:
        from_secret: PRODUCTION_AWS_S3_BUCKET
      access_key:
        from_secret: PRODUCTION_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: PRODUCTION_AWS_SECRET_ACCESS_KEY
      region: us-east-1
      acl: public-read
      source: /go/src/github.com/gravitational/teleport-plugins/*
      target: teleport-plugins/${DRONE_TAG##*-v}/
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/

---
kind: signature
hmac: 58c6b4d9959178e29e9212b2848bf8df06d58f9c59c18e6dcdabc524d1c7a8b1

...
