---
kind: pipeline
type: kubernetes
name: test

trigger:
  event:
    exclude:
      - promote
      - rollback

workspace:
  path: /go

clone:
  disable: true

steps:
  - name: Check out code
    image: golangci/golangci-lint:v1.27.0
    commands:
      - mkdir -p /go/src/github.com/gravitational/teleport-plugins
      - cd /go/src/github.com/gravitational/teleport-plugins
      - git clone https://github.com/gravitational/teleport-plugins.git .
      - git checkout $DRONE_COMMIT
      - echo $DRONE_SOURCE_BRANCH > .drone_source_branch.txt

  - name: Restore cache
    image: meltwater/drone-cache
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    settings:
      restore: true
      bucket:
        from_secret: AWS_S3_BUCKET
      archive_format: gzip
      cache_key: '{{checksum ".drone_source_branch.txt"}}'
      region: us-west-2
      mount:
        - /go/cache
        - /go/pkg/mod

  - name: Run linter
    image: golangci/golangci-lint:v1.27.0
    environment:
      GOCACHE: /go/cache
    commands:
      - cd /go/src/github.com/gravitational/teleport-plugins
      - make lint

  - name: Run tests
    image: golang:1.13.2
    environment:
      GOCACHE: /go/cache
    commands:
      - cd /go/src/github.com/gravitational/teleport-plugins
      - make test

  - name: Save cache
    image: meltwater/drone-cache
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    settings:
      rebuild: true
      bucket:
        from_secret: AWS_S3_BUCKET
      archive_format: gzip
      cache_key: '{{checksum ".drone_source_branch.txt"}}'
      region: us-west-2
      mount:
        - /go/cache
        - /go/pkg/mod

---
kind: pipeline
type: kubernetes
name: build

trigger:
  event:
    - tag
  ref:
    include:
      - refs/tags/teleport-*-v*

depends_on:
  - test

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
  - name: Build artifacts
    image: golang:1.13.2
    commands:
      - git clone https://github.com/gravitational/teleport-plugins.git .
      - git fetch --all --tags
      - git checkout $DRONE_TAG
      - mkdir -p build/
      - make release/access-${DRONE_TAG##*-v}
      - find access/ -iname "*.tar.gz" -print -exec cp {} build/ \;
      - cd build
      - for FILE in *.tar.gz; do sha256sum $FILE > $FILE.sha256; done
      - ls -l .

  - name: Upload to S3
    image: plugins/s3
    settings:
      bucket:
        from_secret: AWS_S3_BUCKET
      access_key:
        from_secret: AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: AWS_SECRET_ACCESS_KEY
      region: us-west-2
      source: /go/src/github.com/gravitational/teleport-plugins/build/*
      target: teleport-plugins/tag/${DRONE_TAG}
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/build

---
kind: pipeline
type: kubernetes
name: promote-artifact

trigger:
  event:
    - promote
  target:
    - production

workspace:
  path: /go/src/github.com/gravitational/teleport-plugins

clone:
  disable: true

steps:
  - name: Download artifact from S3 artifact publishing bucket
    image: amazon/aws-cli
    environment:
      AWS_S3_BUCKET:
        from_secret: AWS_S3_BUCKET
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_REGION: us-west-2
    commands:
      - aws s3 sync s3://$AWS_S3_BUCKET/teleport-plugins/tag/$DRONE_TAG/ .

  - name: Upload artifact to production S3 bucket with public read access
    image: plugins/s3
    settings:
      bucket:
        from_secret: PRODUCTION_AWS_S3_BUCKET
      access_key:
        from_secret: PRODUCTION_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: PRODUCTION_AWS_SECRET_ACCESS_KEY
      region: us-east-1
      acl: public-read
      source: /go/src/github.com/gravitational/teleport-plugins/*
      target: teleport-plugins/${DRONE_TAG##*-v}/
      strip_prefix: /go/src/github.com/gravitational/teleport-plugins/

---
kind: signature
hmac: 646bd046a1e9be9fc3d7a651b62f51bee53fe852a6a1d82c6d6db1b7b901befb

...
