# permissions for end users to view identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: identity-viewer-role
rules:
- apiGroups:
  - auth.teleport.dev
  resources:
  - identities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.teleport.dev
  resources:
  - identities/status
  verbs:
  - get
