---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - auth.teleport.dev
  resources:
  - identities
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.teleport.dev
  resources:
  - identities/finalizers
  verbs:
  - update
- apiGroups:
  - auth.teleport.dev
  resources:
  - identities/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - config.teleport.dev
  resources:
  - sidecars
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.teleport.dev
  resources:
  - sidecars/finalizers
  verbs:
  - update
- apiGroups:
  - config.teleport.dev
  resources:
  - sidecars/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resources.teleport.dev
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.teleport.dev
  resources:
  - roles/finalizers
  verbs:
  - update
- apiGroups:
  - resources.teleport.dev
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - resources.teleport.dev
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resources.teleport.dev
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - resources.teleport.dev
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
