steps:
  - name: 'alpine/helm'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        apk add openssl curl bash git &&
        helm plugin install https://github.com/vbehar/helm3-unittest &&
        helm unittest ./charts/access/email
