# Default values for email.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# replicaCount: 1

image:
  repository: 146628656107.dkr.ecr.us-west-2.amazonaws.com/teleport/access-plugin-email
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

volumes: []
  # - name: password-file
  #   secret:
  #     secretName: teleport-email-plugin-password-file
  #     defaultMode: 0600

volumeMounts: []
  # - name: password-file
  #   mountPath: /var/lib/teleport/plugins/email/smtp_password

#
# Plugin specific options
#
teleport:
  address: auth.example.com:3025
  identitySecretName: ""
  identitySecretPath: "auth_id"

mailgun:
  enabled: false
  domain: sandboxbd81caddef744a69be0e5b544ab0c3bd.mailgun.org
  privateKey: xoxb-11xx

smtp:
  enabled: false
  host: smtp.example.com
  port: 587
  username: username@example.com
  password: ""
  passwordFile: ""

delivery:
  sender: noreply@example.com
  recipients:
    - all@example.com

log:
  output: stdout
  severity: INFO
